name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vite GitHub Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        with:
          public_base_path: "/tictactoe" # Replace with the repo name
          build_path: "./dist"
          package_manager: "npm"
          artifact_name: "github-pages"
          debug_mode: false
